server:
  port: 8004
spring:
  application:
    name: candidate-management
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.248.210:3306/candidate_management?characterEncoding=utf8&useSSL=false
    username: root
    password: root
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: 140.143.56.43
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka

excel:
  position:
    baseName: 个人基本信息
    careerName: 求职意向
    selfName: 自我评价
    workName: 工作经历
    projectName: 项目经验
    educationName: 项目名称：
